name: Books.com.tw Daily Signin

on:
  # Runs automatically every day at 12:00 UTC
  schedule: [{ cron: "0 12 * * *" }]

  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

env:
  INSTALL_FROM: Poetry  # Valid values: Poetry, PyPI
  PYTHON_VERSION: "3.8"  # See https://github.com/actions/python-versions/releases
  POETRY_VERSION: "1.7.1"  # See https://github.com/python-poetry/poetry/releases
  

jobs:
  auto-signin:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Set up chromedriver
        uses: nanasess/setup-chromedriver@v2

      # Poetry Branch
      - name: "[From Poetry] Set up Poetry"
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
        if: ${{ env.INSTALL_FROM == 'Poetry' }}
      - name: "[From Poetry] Install dependencies"
        run: poetry install
        if: ${{ env.INSTALL_FROM == 'Poetry' }}
      - name: "[From Poetry] Run the auto-sign script"
        run: poetry run python ./demo/github-auto-signin.py
        env:
            BAIDU_API_KEY: ${{ secrets.BAIDU_API_KEY }}
            BAIDU_SECRET_KEY: ${{ secrets.BAIDU_SECRET_KEY }}
            BOOKS_TW_USERNAME: ${{ secrets.BOOKS_TW_USERNAME }}
            BOOKS_TW_PASSWORD: ${{ secrets.BOOKS_TW_PASSWORD }}
        if: ${{ env.INSTALL_FROM == 'Poetry' }}

      # PyPI Branch
      - name: "[From PyPI] Install dependencies"
        run: pip install bookstw
        if: ${{ env.INSTALL_FROM == 'PyPI' }}
      - name: "[From PyPI] Run the auto-sign script"
        run: python ./demo/github-auto-signin.py
        env:
            BAIDU_API_KEY: ${{ secrets.BAIDU_API_KEY }}
            BAIDU_SECRET_KEY: ${{ secrets.BAIDU_SECRET_KEY }}
            BOOKS_TW_USERNAME: ${{ secrets.BOOKS_TW_USERNAME }}
            BOOKS_TW_PASSWORD: ${{ secrets.BOOKS_TW_PASSWORD }}
        if: ${{ env.INSTALL_FROM == 'PyPI' }}
